export enum CompanyIndustry {
  AUTOMOTIVE = 'AUTOMOTIVE',

  PHARMACY_COSMETICS = 'PHARMACY_COSMETICS',

  TECHNOLOGICAL_ELECTRONIC = 'TECHNOLOGICAL_ELECTRONIC',

  CLOTHES_ACCESSORIES = 'CLOTHES_ACCESSORIES',

  SPORTS = 'SPORTS',

  CHILDCARE = 'CHILDCARE',

  PETS = 'PETS',

  HOME_GARDEN = 'HOME_GARDEN',

  FOOD_DRINKS = 'FOOD_DRINKS',

  TOYS_HOBBIES = 'TOYS_HOBBIES',

  LEISURE = 'LEISURE',

  CULTURE = 'CULTURE',

  OTHER = 'OTHER',
}
